language: php

dist: trusty

sudo: true

php:
  - 5.6
  - 7.0
  - 7.1
  
env:
  - DB=mysql db_dsn='mysql://root@127.0.0.1/cakephp_test'
  
services:
  - mysql

matrix:
  fast_finish: true

before_script:
  - bash .travis.install-mysql-5.7.sh
  - mysql -u root -e "CREATE DATABASE cakephp_test;"
  - composer update;
  - composer run-script post-install-cmd --no-interaction;

script:
  - vendor/bin/phpunit;

notifications:
  email: false

